services:
  llm-api-for-next-chat:
    build: .
    image: llm-api-for-next-chat/llm-api-for-next-chat:latest
    container_name: llm-api-for-next-chat
    ports:
      - 5000:5000
    restart: unless-stopped
    volumes:
      - ./chatgpt_web/file_cache.json:/app/chatgpt_web/file_cache.json
      - ./theb_ai/Theb_API.json:/app/theb_ai/Theb_API.json
      - ./hugging_chat/config.json:/app/hugging_chat/config.json
      - ./generated_images:/app/generated_images
      - .env:/app/.env
    networks:
      - llms_api

  chatgpt-next-web:
    image: yidadaa/chatgpt-next-web:v2.12.4
    container_name: chatgpt-next-web
    restart: unless-stopped
    depends_on:
      - llm-api-for-next-chat
    ports:
      - 3030:3000
    environment:
      BASE_URL: http://llm-api-for-next-chat:5000/api/openai
      ANTHROPIC_URL: http://llm-api-for-next-chat:5000/api/anthropic
      CUSTOM_MODELS:
        "-all,\
        gpt-4o,\
        gpt-4o-mini,\
        gpt-4-turbo,\
        gpt-4,\
        gpt-3.5-turbo,\
        gpt-3.5,\
        gemma-2-9b,\
        gemma-2-27b,\
        gemini-1.5-pro-latest,\
        gemini-1.5-flash-latest,\
        gemini-pro,\
        gemini-pro-vision,\
        claude-3-5-sonnet-20240620,\
        claude-3-opus-20240229,\
        claude-3-sonnet-20240229,\
        claude-3-haiku-20240307,\
        llama-3.1-405b,\
        llama-3.1-405b-instruct,\
        llama-3.1-70b-instruct,\
        llama-3.1-70b,\
        llama-3.1-8b,\
        llama-3-70b,\
        llama-3-8b,\
        mixtral-8x22b,\
        mixtral-8x7b,\
        mixtral-8x7b-instruct,\
        mistral-7b,\
        mistral-7b-instruct,\
        wizardlm-2-8x22b,\
        dbrx-instruct,\
        qwen-2-72b,\
        qwen-1.5-110b,\
        qwen-1.5-72b,\
        qwen-1.5-32b,\
        qwen-1.5-14b,\
        qwen-1.5-7b,\
        deepseek-llm-67b,\
        yi-1.5-34b-chat,\
        yi-34b,\
        theb-ai,\
        command-r-plus,\
        nous-hermes-2-mixtral-8x7b-dpo,\
        phi-3-mini-4k-instruct"
    env_file:
      - .env
    networks:
      - llms_api


networks:
  llms_api:
    name: llms_api